name: agriworx
description: "A fertilizer simulation game."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  scidart: ^0.0.1
  shared_preferences: ^2.2.1 # needed to store data in local memory
  flutter_riverpod: ^2.5.1 # for caching, dependency injection, state management
  riverpod_annotation: ^2.3.5 # for using riverpod generator
  freezed_annotation: ^2.4.1 # for creating class methods (toString(), etc...)
  json_annotation: ^4.8.1 # for creating .toJson() and .fromJson() methods
  carousel_slider: ^4.2.1
  auto_size_text: ^3.0.0
  syncfusion_flutter_charts: ^25.2.7 # for charts creation
  intl: ^0.19.0
  firebase_core: ^2.31.1 # required for any Firebase service
  firebase_auth: ^4.19.6 # for identifying unique devices
  cloud_firestore: ^4.17.4 # to use firestore database
  envied: ^0.5.4+1 # required to obscure API keys and other sensitive data
  gsheets: ^0.5.0 # working with google sheets
  normal: ^0.7.0
  vector_math: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  riverpod_lint: ^2.3.10
  custom_lint: ^0.6.4
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  freezed: ^2.5.1
  riverpod_generator: ^2.4.0
  envied_generator: ^0.5.4+1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pictures/fertilizers/
    - assets/pictures/soil/
    - assets/pictures/units/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/pictures/logo/icon_pp.png'
  web:
    generate: true
    image_path: "assets/pictures/logo/icon_pp.png"

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  generate: true