// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb4r9bITQuDtVPIhTsQshBh_2xa0d44QQ',
    appId: '1:481764329868:web:7e05512f6facb608816ea9',
    messagingSenderId: '481764329868',
    projectId: 'agriworks-70402',
    authDomain: 'agriworks-70402.firebaseapp.com',
    storageBucket: 'agriworks-70402.appspot.com',
    measurementId: 'G-P3N90Y2G0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwfsQXHZN6fN30Mmpizaq7Tst-rxIyEhI',
    appId: '1:481764329868:android:863979b06ec23017816ea9',
    messagingSenderId: '481764329868',
    projectId: 'agriworks-70402',
    storageBucket: 'agriworks-70402.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLXrKcVpjyELvuYQC4ERvMryplzhPQEcs',
    appId: '1:481764329868:ios:ea0a25445c137c2b816ea9',
    messagingSenderId: '481764329868',
    projectId: 'agriworks-70402',
    storageBucket: 'agriworks-70402.appspot.com',
    iosBundleId: 'com.prosperplay.agriworx',
  );
}
